spring.application.name=ai-service
server.port=8089
spring.config.import=optional:configserver:http://localhost:8888

gemini.api.key=AIzaSyB3ipSVsjNZl9ZAL_2aOIiDNSegiYwdcZY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

resume.service.url=http://localhost:8084

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
